import { ReferralsFilterType } from '@/types'

export const filterTitle = (filterType: ReferralsFilterType) =>
    filterType === 'all'
        ? 'All Referrals'
        : filterType === 'closed-mtd'
        ? 'Closed MTD'
        : filterType === 'closed-today'
        ? 'Closed Today'
        : filterType === 'installation-today'
        ? 'Install Today'
        : filterType === 'closed-wtd'
        ? 'Closed WTD'
        : filterType === 'moving-today'
        ? 'Moving Today'
        : filterType === 'in-progress'
        ? 'In Progress'
        : filterType === 'installation-last-week'
        ? 'Installed Last Week'
        : filterType === 'installation-yesterday'
        ? 'Installed Yesterday'
        : filterType === 'moving-in-one-month'
        ? 'Moving In A Month'
        : filterType === 'moving-in-one-week'
        ? 'Moving Within a Week'
        : filterType === 'new'
        ? 'New'
        : 'Referrals'
